// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGa-H9G_DyOZmXHfcjJu5AdE6qyMlmDkw',
    appId: '1:558499934023:web:aaea6985f6c84d85a12662',
    messagingSenderId: '558499934023',
    projectId: 'auth-493c5',
    authDomain: 'auth-493c5.firebaseapp.com',
    storageBucket: 'auth-493c5.firebasestorage.app',
    measurementId: 'G-82X00CMC3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3oyQn8rRcw72R7qVYYkvK4RRkexVxf8',
    appId: '1:558499934023:android:049a88840e39388ca12662',
    messagingSenderId: '558499934023',
    projectId: 'auth-493c5',
    storageBucket: 'auth-493c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB5sGM5EufDGLE9gIUB_d46QIabF0WeUw',
    appId: '1:558499934023:ios:a1096d6a13a92fe2a12662',
    messagingSenderId: '558499934023',
    projectId: 'auth-493c5',
    storageBucket: 'auth-493c5.firebasestorage.app',
    androidClientId: '558499934023-qrnjp513qhd0fea5jp6qfc1au6g23usi.apps.googleusercontent.com',
    iosClientId: '558499934023-skkmee5jgo1r1vio0ufveitbc9lgk24l.apps.googleusercontent.com',
    iosBundleId: 'com.gt.emailauth',
  );

}